import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/_global/Navbar";
import ContactMe from "./_components/_global/ContactMe";
import ClientLayout from "./_components/_global/ClientLayout";
import AnimateBackGround from "./_components/_global/AnimateBackGround";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "700"],
  display: "swap",
});

const cairo = Cairo({
  subsets: ["arabic"],
  variable: "--font-cairo",
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${cairo.variable} font-sans antialiased`}
      >
        <ClientLayout>
          {/* <AnimateBackGround /> */}
          <Navbar />
          <ContactMe />
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
